/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 91735
 */
public class Frame3 extends javax.swing.JFrame {
    
    
    

         String[][] questions = {
       
       {" Who is Iron Man of INDIA?","Govind Ballabh Pant","Jawaharlal","Subhash Chandra Bose","Sardar Vallabhbhai Patel","Sardar Vallabhbhai Patel"},
       {" Who is the GOD of cricket","MSD","Kapil Dev","Sachin Tendulkar","Virat Kohli","Sachin Tendulkar"},
       {"Akbar married a bride from?","Udaipur","Jaisalmer","Jaipur","Bikaner","Udaipur"},
       {"Guru Nanak was born at?","Purandhar","Amritsarr","Talwandi","Poona","Talwandi"},
       {"first human to space","Yuri Gagarin","Neil Armstrong","Micheal Collins","Buzz Aldrin","Yuri Gagarin"},
       
   
   };
     
   int currentNumber=0;
   
   String[] answers=new String[questions.length];
    /**
     * 
     * Creates new form Frame3
     */
    public Frame3() {
        initComponents();
          question_label.setText("Question 1: "+questions[currentNumber][0]);
        btn_a.setText(questions[currentNumber][1]);
        btn_b.setText(questions[currentNumber][2]);
        btn_c.setText(questions[currentNumber][3]);
        btn_d.setText(questions[currentNumber][4]);
        user_answer.setText("");
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quiz_panel = new javax.swing.JPanel();
        question_label = new javax.swing.JLabel();
        btn_a = new javax.swing.JButton();
        btn_b = new javax.swing.JButton();
        btn_c = new javax.swing.JButton();
        btn_d = new javax.swing.JButton();
        pre = new javax.swing.JButton();
        next = new javax.swing.JButton();
        finish = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        user_answer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        score_panel = new javax.swing.JPanel();
        score_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        question_label.setText("question");

        btn_a.setText("jButton1");
        btn_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aActionPerformed(evt);
            }
        });

        btn_b.setText("jButton2");
        btn_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bActionPerformed(evt);
            }
        });

        btn_c.setText("jButton3");
        btn_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cActionPerformed(evt);
            }
        });

        btn_d.setText("jButton4");
        btn_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dActionPerformed(evt);
            }
        });

        pre.setText("previous");
        pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preActionPerformed(evt);
            }
        });

        next.setText("next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        finish.setText("finish");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });

        jLabel2.setText("Your answer");

        user_answer.setText("jLabel3");

        jLabel1.setText("Module 2 - G.K");

        javax.swing.GroupLayout quiz_panelLayout = new javax.swing.GroupLayout(quiz_panel);
        quiz_panel.setLayout(quiz_panelLayout);
        quiz_panelLayout.setHorizontalGroup(
            quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quiz_panelLayout.createSequentialGroup()
                        .addGroup(quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_d)
                            .addComponent(question_label, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(quiz_panelLayout.createSequentialGroup()
                                .addGroup(quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(46, 46, 46)
                                .addGroup(quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(user_answer, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(quiz_panelLayout.createSequentialGroup()
                                        .addComponent(next)
                                        .addGap(47, 47, 47)
                                        .addComponent(finish)))))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(quiz_panelLayout.createSequentialGroup()
                        .addGroup(quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_c)
                            .addComponent(btn_b)
                            .addComponent(btn_a))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(quiz_panelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        quiz_panelLayout.setVerticalGroup(
            quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(question_label)
                .addGap(18, 18, 18)
                .addComponent(btn_a)
                .addGap(18, 18, 18)
                .addComponent(btn_b)
                .addGap(18, 18, 18)
                .addComponent(btn_c)
                .addGap(18, 18, 18)
                .addComponent(btn_d)
                .addGap(28, 28, 28)
                .addGroup(quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(user_answer))
                .addGap(18, 18, 18)
                .addGroup(quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next)
                    .addComponent(pre)
                    .addComponent(finish))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        score_label.setText("Your score 0");

        javax.swing.GroupLayout score_panelLayout = new javax.swing.GroupLayout(score_panel);
        score_panel.setLayout(score_panelLayout);
        score_panelLayout.setHorizontalGroup(
            score_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(score_panelLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(score_label)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        score_panelLayout.setVerticalGroup(
            score_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(score_panelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(score_label)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quiz_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(score_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quiz_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(score_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aActionPerformed
        // TODO add your handling code here:
         answers[currentNumber]=btn_a.getText();
        user_answer.setText(answers[currentNumber]);
    }//GEN-LAST:event_btn_aActionPerformed

    private void btn_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bActionPerformed
        // TODO add your handling code here:
         answers[currentNumber]=btn_b.getText();
        user_answer.setText(answers[currentNumber]);
    }//GEN-LAST:event_btn_bActionPerformed

    private void btn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cActionPerformed
        // TODO add your handling code here:
         answers[currentNumber]=btn_c.getText();
        user_answer.setText(answers[currentNumber]);
    }//GEN-LAST:event_btn_cActionPerformed

    private void btn_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dActionPerformed
        // TODO add your handling code here:
         answers[currentNumber]=btn_d.getText();
        user_answer.setText(answers[currentNumber]);
    }//GEN-LAST:event_btn_dActionPerformed

    private void preActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preActionPerformed
        // TODO add your handling code here:
           if(currentNumber>0){
        currentNumber--;}
         
        question_label.setText("Question: "+(currentNumber+1)+":"+questions[currentNumber][0]);
        btn_a.setText(questions[currentNumber][1]);
        btn_b.setText(questions[currentNumber][2]);
        btn_c.setText(questions[currentNumber][3]);
        btn_d.setText(questions[currentNumber][4]);
        user_answer.setText(answers[currentNumber]);
        
    }//GEN-LAST:event_preActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
           if(currentNumber < questions.length-1){
                currentNumber++;
        }
    
        question_label.setText("Question: "+(currentNumber+1)+":"+questions[currentNumber][0]);
        btn_a.setText(questions[currentNumber][1]);
        btn_b.setText(questions[currentNumber][2]);
        btn_c.setText(questions[currentNumber][3]);
        btn_d.setText(questions[currentNumber][4]);
        user_answer.setText(answers[currentNumber]);
    }//GEN-LAST:event_nextActionPerformed

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        // TODO add your handling code here:
                  int score=0;
        for(int i=0;i<questions.length;i++){
        if(questions[i][5].equals(answers[i])){
        score++ ;
        }
        }
        score_label.setText("You scored out 5:"+score);
        quiz_panel.setVisible(false);
        score_panel.setVisible(true);
        
        
    }//GEN-LAST:event_finishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_a;
    private javax.swing.JButton btn_b;
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_d;
    private javax.swing.JButton finish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton next;
    private javax.swing.JButton pre;
    private javax.swing.JLabel question_label;
    private javax.swing.JPanel quiz_panel;
    private javax.swing.JLabel score_label;
    private javax.swing.JPanel score_panel;
    private javax.swing.JLabel user_answer;
    // End of variables declaration//GEN-END:variables
}
