/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 91735
 */
public class Frame2 extends javax.swing.JFrame {
    
    
    
    
     String[][] questions = {
       
       {"Man of steel guess who?","Batman","Superman","Aquaman","Flash","Superman"},
       {"Father of Marvel Cinamatic Universe?","Ironman","Captain America","Thor","Hawkeye","Ironman"},
       {"Fastest Man Alive?","Quik Silver","Daredevil","Superman","Flash","Flash"},
       {"Why so serious is famous dioluge by which DC character?","Joker","Green GOblin","Dr.Octopus","Dr.Doom","Joker"},
       
   
   };
     
   int currentNumber=0;
   
   String[] answers=new String[questions.length];

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
        
        question_label.setText("Question 1: "+questions[currentNumber][0]);
        btn_a.setText(questions[currentNumber][1]);
        btn_b.setText(questions[currentNumber][2]);
        btn_c.setText(questions[currentNumber][3]);
        btn_d.setText(questions[currentNumber][4]);
        user_answer.setText("");
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quiz_panel = new javax.swing.JPanel();
        question_label = new javax.swing.JLabel();
        btn_a = new javax.swing.JButton();
        btn_b = new javax.swing.JButton();
        btn_c = new javax.swing.JButton();
        btn_d = new javax.swing.JButton();
        pre = new javax.swing.JButton();
        next = new javax.swing.JButton();
        finish = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        user_answer = new javax.swing.JLabel();
        Lab1 = new javax.swing.JLabel();
        score_panel = new javax.swing.JPanel();
        score_label = new javax.swing.JLabel();
        enough_marks = new javax.swing.JLabel();
        inter_panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        question_label.setText("questions");

        btn_a.setText("option 1");
        btn_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aActionPerformed(evt);
            }
        });

        btn_b.setText("opttion 3");
        btn_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bActionPerformed(evt);
            }
        });

        btn_c.setText("option 3");
        btn_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cActionPerformed(evt);
            }
        });

        btn_d.setText("option 4");
        btn_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dActionPerformed(evt);
            }
        });

        pre.setText("previous");
        pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preActionPerformed(evt);
            }
        });

        next.setText("next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        finish.setText("finish");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });

        jLabel1.setText("Your answer");

        user_answer.setText("jLabel2");

        Lab1.setText("Module 1 - Comic Movies");

        javax.swing.GroupLayout quiz_panelLayout = new javax.swing.GroupLayout(quiz_panel);
        quiz_panel.setLayout(quiz_panelLayout);
        quiz_panelLayout.setHorizontalGroup(
            quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz_panelLayout.createSequentialGroup()
                .addGroup(quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quiz_panelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_d)
                            .addComponent(btn_a)
                            .addComponent(question_label, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(quiz_panelLayout.createSequentialGroup()
                                .addGroup(quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(quiz_panelLayout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(next))
                                    .addGroup(quiz_panelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(user_answer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(61, 61, 61)
                                .addComponent(finish))
                            .addComponent(btn_c)
                            .addComponent(btn_b)))
                    .addGroup(quiz_panelLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(Lab1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        quiz_panelLayout.setVerticalGroup(
            quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quiz_panelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Lab1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(question_label)
                .addGap(28, 28, 28)
                .addComponent(btn_a)
                .addGap(27, 27, 27)
                .addComponent(btn_b)
                .addGap(26, 26, 26)
                .addComponent(btn_c)
                .addGap(34, 34, 34)
                .addComponent(btn_d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(user_answer))
                .addGap(29, 29, 29)
                .addGroup(quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pre)
                    .addComponent(next)
                    .addComponent(finish))
                .addGap(30, 30, 30))
        );

        score_label.setText("YOU SCORE  0");

        javax.swing.GroupLayout inter_panelLayout = new javax.swing.GroupLayout(inter_panel);
        inter_panel.setLayout(inter_panelLayout);
        inter_panelLayout.setHorizontalGroup(
            inter_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );
        inter_panelLayout.setVerticalGroup(
            inter_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jButton1.setText("Module 2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout score_panelLayout = new javax.swing.GroupLayout(score_panel);
        score_panel.setLayout(score_panelLayout);
        score_panelLayout.setHorizontalGroup(
            score_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(score_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(score_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(inter_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(score_panelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(enough_marks, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(score_panelLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(score_label, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        score_panelLayout.setVerticalGroup(
            score_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(score_panelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(enough_marks, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(score_label)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inter_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jButton1.getAccessibleContext().setAccessibleParent(score_label);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quiz_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(score_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quiz_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(score_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aActionPerformed
        // TODO add your handling code here:
         answers[currentNumber]=btn_a.getText();
        user_answer.setText(answers[currentNumber]);
    }//GEN-LAST:event_btn_aActionPerformed

    private void preActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preActionPerformed
        // TODO add your handling code here:
         if(currentNumber>0){
        currentNumber--;}
         
        question_label.setText("Question: "+(currentNumber+1)+":"+questions[currentNumber][0]);
        btn_a.setText(questions[currentNumber][1]);
        btn_b.setText(questions[currentNumber][2]);
        btn_c.setText(questions[currentNumber][3]);
        btn_d.setText(questions[currentNumber][4]);
        user_answer.setText(answers[currentNumber]);
    }//GEN-LAST:event_preActionPerformed

    private void btn_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dActionPerformed
        // TODO add your handling code here:
         answers[currentNumber]=btn_d.getText();
        user_answer.setText(answers[currentNumber]);
    }//GEN-LAST:event_btn_dActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
         if(currentNumber < questions.length-1){
                currentNumber++;
        }
    
        question_label.setText("Question: "+(currentNumber+1)+":"+questions[currentNumber][0]);
        btn_a.setText(questions[currentNumber][1]);
        btn_b.setText(questions[currentNumber][2]);
        btn_c.setText(questions[currentNumber][3]);
        btn_d.setText(questions[currentNumber][4]);
        user_answer.setText(answers[currentNumber]);
    }//GEN-LAST:event_nextActionPerformed

    private void btn_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bActionPerformed
        // TODO add your handling code here:
         answers[currentNumber]=btn_b.getText();
        user_answer.setText(answers[currentNumber]);
    }//GEN-LAST:event_btn_bActionPerformed

    private void btn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cActionPerformed
        // TODO add your handling code here:
         answers[currentNumber]=btn_c.getText();
        user_answer.setText(answers[currentNumber]);
    }//GEN-LAST:event_btn_cActionPerformed
    
    int score=0;
    
   
    
    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        // TODO add your handling code here:
          
        for(int i=0;i<questions.length;i++){
        if(questions[i][5].equals(answers[i])){
        score++ ;
        }
        }
        score_label.setText("You scored out 4:"+score);
        quiz_panel.setVisible(false);
        score_panel.setVisible(true);
        inter_panel.setVisible(true);
        
        
        if(score>=3){
        enough_marks.setText("you have scored enough marks to enter in Module 2");
        
        }
        else{
            enough_marks.setText("you have NOT scored enough marks to enter in Module 2");
        }
       
   
        
    }//GEN-LAST:event_finishActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(score>=3){

            Frame3 sc2=new Frame3();
            sc2.show();
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lab1;
    private javax.swing.JButton btn_a;
    private javax.swing.JButton btn_b;
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_d;
    private javax.swing.JLabel enough_marks;
    public javax.swing.JButton finish;
    private javax.swing.JPanel inter_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton next;
    private javax.swing.JButton pre;
    private javax.swing.JLabel question_label;
    private javax.swing.JPanel quiz_panel;
    private javax.swing.JLabel score_label;
    private javax.swing.JPanel score_panel;
    private javax.swing.JLabel user_answer;
    // End of variables declaration//GEN-END:variables
}
